INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Afghanistan', 'AF', 'Kabul', 2837743, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Sudan', 'SD', 'Khartoum', 43849269, 'https://flagcdn.com/w320/sd.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Burundi', 'BI', 'Gitega', 11890781, 'https://flagcdn.com/w320/bi.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Mexico', 'MX', 'Mexico City', 128932753, 'https://flagcdn.com/w320/mx.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Cuba', 'CU', 'Havana', 11326616, 'https://flagcdn.com/w320/cu.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Serbia', 'RS', 'Belgrade', 6908224, 'https://flagcdn.com/w320/rs.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Monaco', 'MC', 'Monaco', 39244, 'https://flagcdn.com/w320/mc.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Bhutan', 'BT', 'Thimphu', 771612, 'https://flagcdn.com/w320/bt.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Guyana', 'GY', 'Georgetown', 786559, 'https://flagcdn.com/w320/gy.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('South Georgia', 'GS', 'King Edward Point', 30, 'https://flagcdn.com/w320/gs.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Bosnia and Herzegovina', 'BA', 'Sarajevo', 3280815, 'https://flagcdn.com/w320/ba.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Brunei', 'BN', 'Bandar Seri Begawan', 437483, 'https://flagcdn.com/w320/bn.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Pakistan', 'PK', 'Islamabad', 220892331, 'https://flagcdn.com/w320/pk.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Kenya', 'KE', 'Nairobi', 53771300, 'https://flagcdn.com/w320/ke.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Puerto Rico', 'PR', 'San Juan', 3194034, 'https://flagcdn.com/w320/pr.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Somalia', 'SO', 'Mogadishu', 15893219, 'https://flagcdn.com/w320/so.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Svalbard and Jan Mayen', 'SJ', 'Longyearbyen', 2562, 'https://flagcdn.com/w320/sj.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Sierra Leone', 'SL', 'Freetown', 7976985, 'https://flagcdn.com/w320/sl.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('French Polynesia', 'PF', 'Papeetē', 280904, 'https://flagcdn.com/w320/pf.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Azerbaijan', 'AZ', 'Baku', 10110116, 'https://flagcdn.com/w320/az.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Cook Islands', 'CK', 'Avarua', 18100, 'https://flagcdn.com/w320/ck.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Peru', 'PE', 'Lima', 32971846, 'https://flagcdn.com/w320/pe.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Bouvet Island', 'BV', null, 0, 'https://flagcdn.com/w320/bv.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Northern Mariana Islands', 'MP', 'Saipan', 57557, 'https://flagcdn.com/w320/mp.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Angola', 'AO', 'Luanda', 32866268, 'https://flagcdn.com/w320/ao.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Republic of the Congo', 'CG', 'Brazzaville', 89561404, 'https://flagcdn.com/w320/cg.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('South Sudan', 'SS', 'Juba', 11193729, 'https://flagcdn.com/w320/ss.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Saint Martin', 'MF', 'Marigot', 38659, 'https://flagcdn.com/w320/mf.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Turkey', 'TR', 'Ankara', 84339067, 'https://flagcdn.com/w320/tr.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Anguilla', 'AI', 'The Valley', 13452, 'https://flagcdn.com/w320/ai.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Saint Kitts and Nevis', 'KN', 'Basseterre', 53192, 'https://flagcdn.com/w320/kn.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Aruba', 'AW', 'Oranjestad', 106766, 'https://flagcdn.com/w320/aw.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Turks and Caicos Islands', 'TC', 'Cockburn Town', 38718, 'https://flagcdn.com/w320/tc.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Taiwan', 'TW', 'Taipei', 23503349, 'https://flagcdn.com/w320/tw.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Sweden', 'SE', 'Stockholm', 10353442, 'https://flagcdn.com/w320/se.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Liberia', 'LR', 'Monrovia', 5057677, 'https://flagcdn.com/w320/lr.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Venezuela', 'VE', 'Caracas', 28435943, 'https://flagcdn.com/w320/ve.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('United States Virgin Islands', 'VI', 'Charlotte Amalie', 106290, 'https://flagcdn.com/w320/vi.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Bermuda', 'BM', 'Hamilton', 63903, 'https://flagcdn.com/w320/bm.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Albania', 'AL', 'Tirana', 2837743, 'https://flagcdn.com/w320/al.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Hong Kong', 'HK', 'City of Victoria', 7500700, 'https://flagcdn.com/w320/hk.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Luxembourg', 'LU', 'Luxembourg', 632275, 'https://flagcdn.com/w320/lu.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Eritrea', 'ER', 'Asmara', 5352000, 'https://flagcdn.com/w320/er.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Colombia', 'CO', 'Bogotá', 50882884, 'https://flagcdn.com/w320/co.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Caribbean Netherlands', 'BQ', 'Kralendijk', 25987, 'https://flagcdn.com/w320/bq.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Mongolia', 'MN', 'Ulan Bator', 3278292, 'https://flagcdn.com/w320/mn.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Yemen', 'YE', 'Sana''a', 29825968, 'https://flagcdn.com/w320/ye.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Lebanon', 'LB', 'Beirut', 6825442, 'https://flagcdn.com/w320/lb.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Antigua and Barbuda', 'AG', 'Saint John''s', 97928, 'https://flagcdn.com/w320/ag.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Vietnam', 'VN', 'Hanoi', 97338583, 'https://flagcdn.com/w320/vn.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Palau', 'PW', 'Ngerulmud', 18092, 'https://flagcdn.com/w320/pw.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Jersey', 'JE', 'Saint Helier', 100800, 'https://flagcdn.com/w320/je.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Trinidad and Tobago', 'TT', 'Port of Spain', 1399491, 'https://flagcdn.com/w320/tt.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Israel', 'IL', 'Jerusalem', 9216900, 'https://flagcdn.com/w320/il.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Bulgaria', 'BG', 'Sofia', 6927288, 'https://flagcdn.com/w320/bg.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Portugal', 'PT', 'Lisbon', 10305564, 'https://flagcdn.com/w320/pt.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Gibraltar', 'GI', 'Gibraltar', 33691, 'https://flagcdn.com/w320/gi.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('San Marino', 'SM', 'City of San Marino', 33938, 'https://flagcdn.com/w320/sm.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Singapore', 'SG', 'Singapore', 5685807, 'https://flagcdn.com/w320/sg.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Sint Maarten', 'SX', 'Philipsburg', 40812, 'https://flagcdn.com/w320/sx.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Saudi Arabia', 'SA', 'Riyadh', 34813867, 'https://flagcdn.com/w320/sa.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Ghana', 'GH', 'Accra', 31072945, 'https://flagcdn.com/w320/gh.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Moldova', 'MD', 'Chișinău', 2617820, 'https://flagcdn.com/w320/md.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Chad', 'TD', 'N''Djamena', 16425859, 'https://flagcdn.com/w320/td.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Antarctica', 'AQ', null, 1000, 'https://flagcdn.com/w320/aq.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('United Kingdom', 'GB', 'London', 67215293, 'https://flagcdn.com/w320/gb.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Papua New Guinea', 'PG', 'Port Moresby', 8947027, 'https://flagcdn.com/w320/pg.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('French Southern and Antarctic Lands', 'TF', 'Port-aux-Français', 400, 'https://flagcdn.com/w320/tf.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('United States Minor Outlying Islands', 'UM', null, 300, 'https://flagcdn.com/w320/um.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Belize', 'BZ', 'Belmopan', 397621, 'https://flagcdn.com/w320/bz.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Comoros', 'KM', 'Moroni', 869595, 'https://flagcdn.com/w320/km.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Burkina Faso', 'BF', 'Ouagadougou', 20903278, 'https://flagcdn.com/w320/bf.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Faroe Islands', 'FO', 'Tórshavn', 48865, 'https://flagcdn.com/w320/fo.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Guinea', 'GN', 'Conakry', 13132792, 'https://flagcdn.com/w320/gn.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('India', 'IN', 'New Delhi', 1380004385, 'https://flagcdn.com/w320/in.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Curaçao', 'CW', 'Willemstad', 155014, 'https://flagcdn.com/w320/cw.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Togo', 'TG', 'Lomé', 8278737, 'https://flagcdn.com/w320/tg.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Tunisia', 'TN', 'Tunis', 11818618, 'https://flagcdn.com/w320/tn.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Saint Barthélemy', 'BL', 'Gustavia', 4255, 'https://flagcdn.com/w320/bl.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Indonesia', 'ID', 'Jakarta', 273523621, 'https://flagcdn.com/w320/id.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Micronesia', 'FM', 'Palikir', 115021, 'https://flagcdn.com/w320/fm.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Austria', 'AT', 'Vienna', 8917205, 'https://flagcdn.com/w320/at.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Tajikistan', 'TJ', 'Dushanbe', 9537642, 'https://flagcdn.com/w320/tj.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('DR Congo', 'CD', 'Kinshasa', 89561404, 'https://flagcdn.com/w320/cd.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Mayotte', 'YT', 'Mamoudzou', 226915, 'https://flagcdn.com/w320/yt.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Réunion', 'RE', 'Saint-Denis', 840974, 'https://flagcdn.com/w320/re.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Romania', 'RO', 'Bucharest', 19286123, 'https://flagcdn.com/w320/ro.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Qatar', 'QA', 'Doha', 2881060, 'https://flagcdn.com/w320/qa.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Lithuania', 'LT', 'Vilnius', 2794700, 'https://flagcdn.com/w320/lt.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('China', 'CN', 'Beijing', 1402112000, 'https://flagcdn.com/w320/cn.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('New Zealand', 'NZ', 'Wellington', 5084300, 'https://flagcdn.com/w320/nz.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Norfolk Island', 'NF', 'Kingston', 2302, 'https://flagcdn.com/w320/nf.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Mauritania', 'MR', 'Nouakchott', 4649660, 'https://flagcdn.com/w320/mr.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Uzbekistan', 'UZ', 'Tashkent', 34232050, 'https://flagcdn.com/w320/uz.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Finland', 'FI', 'Helsinki', 5530719, 'https://flagcdn.com/w320/fi.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Cameroon', 'CM', 'Yaoundé', 26545864, 'https://flagcdn.com/w320/cm.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Heard Island and McDonald Islands', 'HM', null, 0, 'https://flagcdn.com/w320/hm.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Dominica', 'DM', 'Roseau', 71991, 'https://flagcdn.com/w320/dm.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Iceland', 'IS', 'Reykjavik', 366425, 'https://flagcdn.com/w320/is.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Oman', 'OM', 'Muscat', 5106622, 'https://flagcdn.com/w320/om.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('North Macedonia', 'MK', 'Skopje', 2077132, 'https://flagcdn.com/w320/mk.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Liechtenstein', 'LI', 'Vaduz', 38137, 'https://flagcdn.com/w320/li.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Spain', 'ES', 'Madrid', 47351567, 'https://flagcdn.com/w320/es.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Greece', 'GR', 'Athens', 10715549, 'https://flagcdn.com/w320/gr.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Paraguay', 'PY', 'Asunción', 7132530, 'https://flagcdn.com/w320/py.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Bahrain', 'BH', 'Manama', 1701583, 'https://flagcdn.com/w320/bh.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Niue', 'NU', 'Alofi', 1470, 'https://flagcdn.com/w320/nu.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Senegal', 'SN', 'Dakar', 16743930, 'https://flagcdn.com/w320/sn.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Montserrat', 'MS', 'Plymouth', 4922, 'https://flagcdn.com/w320/ms.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Latvia', 'LV', 'Riga', 1901548, 'https://flagcdn.com/w320/lv.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Tokelau', 'TK', 'Fakaofo', 1411, 'https://flagcdn.com/w320/tk.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Japan', 'JP', 'Tokyo', 125836021, 'https://flagcdn.com/w320/jp.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Central African Republic', 'CF', 'Bangui', 4829764, 'https://flagcdn.com/w320/cf.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Gabon', 'GA', 'Libreville', 2225728, 'https://flagcdn.com/w320/ga.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Iraq', 'IQ', 'Baghdad', 40222503, 'https://flagcdn.com/w320/iq.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Isle of Man', 'IM', 'Douglas', 85032, 'https://flagcdn.com/w320/im.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Myanmar', 'MM', 'Naypyidaw', 54409794, 'https://flagcdn.com/w320/mm.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Montenegro', 'ME', 'Podgorica', 621718, 'https://flagcdn.com/w320/me.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Nauru', 'NR', 'Yaren', 10834, 'https://flagcdn.com/w320/nr.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Vanuatu', 'VU', 'Port Vila', 307150, 'https://flagcdn.com/w320/vu.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('France', 'FR', 'Paris', 67391582, 'https://flagcdn.com/w320/fr.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Zimbabwe', 'ZW', 'Harare', 14862927, 'https://flagcdn.com/w320/zw.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Philippines', 'PH', 'Manila', 109581085, 'https://flagcdn.com/w320/ph.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Slovakia', 'SK', 'Bratislava', 5458827, 'https://flagcdn.com/w320/sk.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Australia', 'AU', 'Canberra', 25687041, 'https://flagcdn.com/w320/au.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Ivory Coast', 'CI', 'Yamoussoukro', 26378275, 'https://flagcdn.com/w320/ci.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('British Indian Ocean Territory', 'IO', 'Diego Garcia', 3000, 'https://flagcdn.com/w320/io.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Eswatini', 'SZ', 'Mbabane', 1160164, 'https://flagcdn.com/w320/sz.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Rwanda', 'RW', 'Kigali', 12952209, 'https://flagcdn.com/w320/rw.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Benin', 'BJ', 'Porto-Novo', 12123198, 'https://flagcdn.com/w320/bj.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('British Virgin Islands', 'VG', 'Road Town', 30237, 'https://flagcdn.com/w320/vg.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Uganda', 'UG', 'Kampala', 45741000, 'https://flagcdn.com/w320/ug.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Ireland', 'IE', 'Dublin', 4994724, 'https://flagcdn.com/w320/ie.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Iran', 'IR', 'Tehran', 83992953, 'https://flagcdn.com/w320/ir.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Slovenia', 'SI', 'Ljubljana', 2100126, 'https://flagcdn.com/w320/si.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Mali', 'ML', 'Bamako', 20250834, 'https://flagcdn.com/w320/ml.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Switzerland', 'CH', 'Bern', 17500657, 'https://flagcdn.com/w320/ch.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('American Samoa', 'AS', 'Pago Pago', 55197, 'https://flagcdn.com/w320/as.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Uruguay', 'UY', 'Montevideo', 3473727, 'https://flagcdn.com/w320/uy.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Guam', 'GU', 'Hagåtña', 168783, 'https://flagcdn.com/w320/gu.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Suriname', 'SR', 'Paramaribo', 586634, 'https://flagcdn.com/w320/sr.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Ukraine', 'UA', 'Kyiv', 44134693, 'https://flagcdn.com/w320/ua.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Czechia', 'CZ', 'Prague', 10698896, 'https://flagcdn.com/w320/cz.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Honduras', 'HN', 'Tegucigalpa', 9904608, 'https://flagcdn.com/w320/hn.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Samoa', 'WS', 'Apia', 198410, 'https://flagcdn.com/w320/ws.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Laos', 'LA', 'Vientiane', 7275556, 'https://flagcdn.com/w320/la.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Cape Verde', 'CV', 'Praia', 555988, 'https://flagcdn.com/w320/cv.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Ethiopia', 'ET', 'Addis Ababa', 114963583, 'https://flagcdn.com/w320/et.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Bangladesh', 'BD', 'Dhaka', 164689383, 'https://flagcdn.com/w320/bd.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'Jamestown', 53192, 'https://flagcdn.com/w320/sh.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Belarus', 'BY', 'Minsk', 9398861, 'https://flagcdn.com/w320/by.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Croatia', 'HR', 'Zagreb', 4047200, 'https://flagcdn.com/w320/hr.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Kuwait', 'KW', 'Kuwait City', 4270563, 'https://flagcdn.com/w320/kw.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('French Guiana', 'GF', 'Cayenne', 254541, 'https://flagcdn.com/w320/gf.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Morocco', 'MA', 'Rabat', 36910558, 'https://flagcdn.com/w320/ma.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Russia', 'RU', 'Moscow', 144104080, 'https://flagcdn.com/w320/ru.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Estonia', 'EE', 'Tallinn', 1331057, 'https://flagcdn.com/w320/ee.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Sri Lanka', 'LK', 'Sri Jayawardenepura Kotte', 21919000, 'https://flagcdn.com/w320/lk.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('New Caledonia', 'NC', 'Nouméa', 271960, 'https://flagcdn.com/w320/nc.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Poland', 'PL', 'Warsaw', 37950802, 'https://flagcdn.com/w320/pl.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Madagascar', 'MG', 'Antananarivo', 27691019, 'https://flagcdn.com/w320/mg.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Costa Rica', 'CR', 'San José', 5094114, 'https://flagcdn.com/w320/cr.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('El Salvador', 'SV', 'San Salvador', 6486201, 'https://flagcdn.com/w320/sv.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Macau', 'MO', null, 649342, 'https://flagcdn.com/w320/mo.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Andorra', 'AD', 'Andorra la Vella', 77265, 'https://flagcdn.com/w320/ad.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Italy', 'IT', 'Rome', 59554023, 'https://flagcdn.com/w320/it.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Namibia', 'NA', 'Windhoek', 2540916, 'https://flagcdn.com/w320/na.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Seychelles', 'SC', 'Victoria', 98462, 'https://flagcdn.com/w320/sc.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Panama', 'PA', 'Panama City', 4314768, 'https://flagcdn.com/w320/pa.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Haiti', 'HT', 'Port-au-Prince', 11402533, 'https://flagcdn.com/w320/ht.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Argentina', 'AR', 'Buenos Aires', 45376763, 'https://flagcdn.com/w320/ar.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Niger', 'NE', 'Niamey', 24206636, 'https://flagcdn.com/w320/ne.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Malawi', 'MW', 'Lilongwe', 19129955, 'https://flagcdn.com/w320/mw.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Pitcairn Islands', 'PN', 'Adamstown', 56, 'https://flagcdn.com/w320/pn.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Germany', 'DE', 'Berlin', 83240525, 'https://flagcdn.com/w320/de.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Kiribati', 'KI', 'South Tarawa', 119446, 'https://flagcdn.com/w320/ki.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Syria', 'SY', 'Damascus', 17500657, 'https://flagcdn.com/w320/sy.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Marshall Islands', 'MH', 'Majuro', 59194, 'https://flagcdn.com/w320/mh.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Hungary', 'HU', 'Budapest', 9749763, 'https://flagcdn.com/w320/hu.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Cayman Islands', 'KY', 'George Town', 65720, 'https://flagcdn.com/w320/ky.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Denmark', 'DK', 'Copenhagen', 5831404, 'https://flagcdn.com/w320/dk.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Saint Lucia', 'LC', 'Castries', 183629, 'https://flagcdn.com/w320/lc.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Bolivia', 'BO', 'Sucre', 11673029, 'https://flagcdn.com/w320/bo.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Djibouti', 'DJ', 'Djibouti', 988002, 'https://flagcdn.com/w320/dj.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('South Africa', 'ZA', 'Pretoria', 59308690, 'https://flagcdn.com/w320/za.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Nigeria', 'NG', 'Abuja', 206139587, 'https://flagcdn.com/w320/ng.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('São Tomé and Príncipe', 'ST', 'São Tomé', 219161, 'https://flagcdn.com/w320/st.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Nicaragua', 'NI', 'Managua', 6624554, 'https://flagcdn.com/w320/ni.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Guadeloupe', 'GP', 'Basse-Terre', 400132, 'https://flagcdn.com/w320/gp.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Saint Pierre and Miquelon', 'PM', 'Saint-Pierre', 6069, 'https://flagcdn.com/w320/pm.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Ecuador', 'EC', 'Quito', 17643060, 'https://flagcdn.com/w320/ec.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Greenland', 'GL', 'Nuuk', 56367, 'https://flagcdn.com/w320/gl.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Grenada', 'GD', 'St. George''s', 112519, 'https://flagcdn.com/w320/gd.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Bahamas', 'BS', 'Nassau', 393248, 'https://flagcdn.com/w320/bs.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Chile', 'CL', 'Santiago', 19116209, 'https://flagcdn.com/w320/cl.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Malaysia', 'MY', 'Kuala Lumpur', 32365998, 'https://flagcdn.com/w320/my.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Tuvalu', 'TV', 'Funafuti', 11792, 'https://flagcdn.com/w320/tv.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Christmas Island', 'CX', 'Flying Fish Cove', 2072, 'https://flagcdn.com/w320/cx.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Solomon Islands', 'SB', 'Honiara', 686878, 'https://flagcdn.com/w320/sb.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Tanzania', 'TZ', 'Dodoma', 59734213, 'https://flagcdn.com/w320/tz.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('North Korea', 'KP', 'Pyongyang', 25778815, 'https://flagcdn.com/w320/kp.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Guinea-Bissau', 'GW', 'Bissau', 1967998, 'https://flagcdn.com/w320/gw.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Kosovo', 'XK', 'Pristina', 1775378, 'https://flagcdn.com/w320/xk.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Vatican City', 'VA', 'Vatican City', 451, 'https://flagcdn.com/w320/va.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Norway', 'NO', 'Oslo', 5379475, 'https://flagcdn.com/w320/no.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Palestine', 'PS', 'Ramallah', 4803269, 'https://flagcdn.com/w320/ps.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Cocos (Keeling) Islands', 'CC', 'West Island', 544, 'https://flagcdn.com/w320/cc.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Jamaica', 'JM', 'Kingston', 2961161, 'https://flagcdn.com/w320/jm.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Egypt', 'EG', 'Cairo', 102334403, 'https://flagcdn.com/w320/eg.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Cambodia', 'KH', 'Phnom Penh', 16718971, 'https://flagcdn.com/w320/kh.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Mauritius', 'MU', 'Port Louis', 1265740, 'https://flagcdn.com/w320/mu.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Gambia', 'GM', 'Banjul', 2416664, 'https://flagcdn.com/w320/gm.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Equatorial Guinea', 'GQ', 'Malabo', 1402985, 'https://flagcdn.com/w320/gq.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Lesotho', 'LS', 'Maseru', 2142252, 'https://flagcdn.com/w320/ls.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Martinique', 'MQ', 'Fort-de-France', 378243, 'https://flagcdn.com/w320/mq.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('United States', 'US', 'Washington, D.C.', 329484123, 'https://flagcdn.com/w320/us.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Western Sahara', 'EH', 'El Aaiún', 510713, 'https://flagcdn.com/w320/eh.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('United Arab Emirates', 'AE', 'Abu Dhabi', 9890400, 'https://flagcdn.com/w320/ae.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Mozambique', 'MZ', 'Maputo', 31255435, 'https://flagcdn.com/w320/mz.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Algeria', 'DZ', 'Algiers', 510713, 'https://flagcdn.com/w320/dz.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Zambia', 'ZM', 'Lusaka', 18383956, 'https://flagcdn.com/w320/zm.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Guatemala', 'GT', 'Guatemala City', 16858333, 'https://flagcdn.com/w320/gt.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('South Korea', 'KR', 'Seoul', 51780579, 'https://flagcdn.com/w320/kr.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Kyrgyzstan', 'KG', 'Bishkek', 6591600, 'https://flagcdn.com/w320/kg.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Timor-Leste', 'TL', 'Dili', 1318442, 'https://flagcdn.com/w320/tl.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Åland Islands', 'AX', 'Mariehamn', 29458, 'https://flagcdn.com/w320/ax.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Jordan', 'JO', 'Amman', 10203140, 'https://flagcdn.com/w320/jo.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Malta', 'MT', 'Valletta', 525285, 'https://flagcdn.com/w320/mt.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Cyprus', 'CY', 'Nicosia', 1207361, 'https://flagcdn.com/w320/cy.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Falkland Islands', 'FK', 'Stanley', 2563, 'https://flagcdn.com/w320/fk.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Kazakhstan', 'KZ', 'Nur-Sultan', 18754440, 'https://flagcdn.com/w320/kz.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Botswana', 'BW', 'Gaborone', 2351625, 'https://flagcdn.com/w320/bw.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Saint Vincent and the Grenadines', 'VC', 'Kingstown', 110947, 'https://flagcdn.com/w320/vc.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Barbados', 'BB', 'Bridgetown', 287371, 'https://flagcdn.com/w320/bb.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Tonga', 'TO', 'Nuku''alofa', 105697, 'https://flagcdn.com/w320/to.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Thailand', 'TH', 'Bangkok', 69799978, 'https://flagcdn.com/w320/th.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Belgium', 'BE', 'Brussels', 11555997, 'https://flagcdn.com/w320/be.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Canada', 'CA', 'Ottawa', 38005238, 'https://flagcdn.com/w320/ca.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Georgia', 'GE', 'Tbilisi', 3714000, 'https://flagcdn.com/w320/ge.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Wallis and Futuna', 'WF', 'Mata-Utu', 11750, 'https://flagcdn.com/w320/wf.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Fiji', 'FJ', 'Suva', 896444, 'https://flagcdn.com/w320/fj.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Netherlands', 'NL', 'Amsterdam', 16655799, 'https://flagcdn.com/w320/nl.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Armenia', 'AM', 'Yerevan', 2963234, 'https://flagcdn.com/w320/am.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Dominican Republic', 'DO', 'Santo Domingo', 10847904, 'https://flagcdn.com/w320/do.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Guernsey', 'GG', 'St. Peter Port', 62999, 'https://flagcdn.com/w320/gg.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Turkmenistan', 'TM', 'Ashgabat', 6031187, 'https://flagcdn.com/w320/tm.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Nepal', 'NP', 'Kathmandu', 29136808, 'https://flagcdn.com/w320/np.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Maldives', 'MV', 'Malé', 540542, 'https://flagcdn.com/w320/mv.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Libya', 'LY', 'Tripoli', 6871287, 'https://flagcdn.com/w320/ly.png');
INSERT INTO country (name, country_code, capital, population, flag_file_url) VALUES ('Brazil', 'BR', 'Brasília', 212559409, 'https://flagcdn.com/w320/br.png');
